interface ExportOptions {
  recommendationId: string;
  headline: string;
  body: string;
  imageUrl?: string | null;
  ctaText: string;
  destinationUrl: string;
  baseUrl: string;
}

export function generateHtmlSnippet(options: ExportOptions): string {
  const trackingPixelUrl = `${options.baseUrl}/api/track/impression?rid=${options.recommendationId}`;
  const clickUrl = `${options.baseUrl}/api/track/click?rid=${options.recommendationId}&dest=${encodeURIComponent(options.destinationUrl)}`;

  return `<!-- Ad Unit - Generated by Creator Ad Network -->
<div style="border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; max-width: 600px; font-family: system-ui, -apple-system, sans-serif; margin: 16px 0;">
  ${
    options.imageUrl
      ? `<img src="${options.imageUrl}" alt="${options.headline}" style="width: 100%; border-radius: 4px; margin-bottom: 12px;" />`
      : ""
  }
  <h3 style="margin: 0 0 8px 0; font-size: 18px; font-weight: 600; color: #111827;">
    ${options.headline}
  </h3>
  <p style="margin: 0 0 12px 0; font-size: 14px; line-height: 1.5; color: #4b5563;">
    ${options.body}
  </p>
  <a href="${clickUrl}"
     target="_blank"
     rel="noopener noreferrer sponsored"
     style="display: inline-block; background-color: #2563eb; color: white; padding: 8px 16px; border-radius: 6px; text-decoration: none; font-size: 14px; font-weight: 500;">
    ${options.ctaText}
  </a>
  <img src="${trackingPixelUrl}" width="1" height="1" style="position: absolute; left: -9999px;" alt="" />
</div>
<!-- End Ad Unit -->`.trim();
}
